<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>MultiWindowShare</AssemblyName>
    <RootNamespace>MultiWindowShare</RootNamespace>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\AppIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MultiWindowShare.Core\MultiWindowShare.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Vortice.D3DCompiler" Version="3.8.3" />
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
  </ItemGroup>

</Project>
